---

DOCKER_BUILD_DIR: "{{playbook_dir}}/build"

SAMBA_REALM: "samdom.example.com"
SAMBA_DOMAIN: "SAMDOM"

SAMBA_USERNAME: "Administrator"
SAMBA_PASSWORD: "Password01@"

SAMBA_DNS_FORWARDER: 8.8.8.8
samba_dns_backend: 'SAMBA_INTERNAL'  # SAMBA_INTERNAL|BIND9_FLATFILE|BIND9_DLZ|NONE
SAMBA_BACKEND_STORE: "mdb"

SAMBA_REPO_URL: https://gitlab.com/catalyst-samba/samba.git
SAMBA_REPO_VERSION: master
SAMBA_REPO_DIR: /home/samba/samba

SAMBA_VOLUME: "/home/samba/volume"
SAMBA_BASE_IMAGE: "samba-ubuntu1804"

NUM_USERS: 5000
NUM_GROUPS: "{{ (NUM_USERS * 0.1)|int }}"
NUM_MAX_MEMBERS: "{{ NUM_USERS }}"
NUM_AVERAGE_GEOUPS_PER_USER: 6

image: all

