#!/usr/bin/env ansible-playbook

---
- hosts: localhost
  become: false
  gather_facts: false
  any_errors_fatal: yes
  vars:

    DOCKER_BUILD_DIR: "{{playbook_dir}}/build"

    SAMBA_REALM: "SAMDOM.EXAMPLE.COM"
    SAMBA_DOMAIN: "SAMDOM"
    SAMBA_USERNAME: "Administrator"
    SAMBA_PASSWORD: "Password01@"
    SAMBA_BACKEND_STORE: "mdb"

    SAMBA_REPO_URL: https://gitlab.com/catalyst-samba/samba.git
    SAMBA_REPO_BRANCH: master
    SAMBA_REPO_DIR: /home/samba/samba

    SAMBA_BASE_IMAGE: "samba-ubuntu1804"

    image: all

  tasks:

    - name: create tmp dir
      file:
        path: "{{DOCKER_BUILD_DIR}}"
        state: directory
        mode: 0755
      tags:
        - render

    - name: render templates
      template:
        src: "{{item}}"
        dest: "{{DOCKER_BUILD_DIR}}/{{item|basename}}"
        mode: 0755
        force: yes
      with_fileglob:
        - "templates/*.sh"
        - "templates/Dockerfile-*"
      tags:
        - render

    - name: build images
      docker_image:
        path: "{{DOCKER_BUILD_DIR}}"
        dockerfile: "Dockerfile-{{item}}"
        name:  "{{item}}"
        tag: latest
        state: build
        nocache: no
        pull: no  # pull FROM image while build
        push: no
        force: "{{ force|default(false) }}"
        rm: yes  # rm intermediate containers after build
      when: image == 'all' or image == item
      loop:
        - samba-common
        - samba-dc
