---
version: "3"

services:
  pdc:
    image: samba-env:ubuntu1604
    container_name: dc0
    hostname: dc0
    user: root
    volumes:
      - ~/samba:/home/samba/samba
    working_dir: /home/samba/samba
    dns_search:
      - samdom.example.com
    domainname: samdom.example.com
    stdin_open: true
    tty: true
