---
version: "3"

networks:
  samnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24


services:
  pdc:
    image: samba-pdc
    container_name: dc0
    hostname: dc0
    networks:
      samnet:
        ipv4_address: 10.10.10.10
    dns:
      - 10.10.10.10
    dns_search:
      - samdom.example.com
    domainname: samdom.example.com
    privileged: true
