#!/usr/bin/env ansible-playbook

---
- hosts: localhost
  become: false
  gather_facts: false
  any_errors_fatal: yes
  tasks:

    - name: create tmp dir
      file:
        path: "{{DOCKER_BUILD_DIR}}"
        state: directory
        mode: 0755
      tags:
        - render

    - name: render templates
      template:
        src: "{{item}}"
        dest: "{{DOCKER_BUILD_DIR}}/{{item|basename}}"
        mode: 0755
        force: yes
      with_fileglob:
        - "templates/*"
      tags:
        - render
