FROM {{SAMBA_BASE_IMAGE}}

# make test can not work with root, so we have to create a new user

ENV USER=samba LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 CC="ccache gcc" DEBIAN_FRONTEND=noninteractive PATH="/usr/local/samba/sbin:/usr/local/samba/bin:${PATH}"

RUN useradd -m -s /bin/bash samba && \
    mkdir -p /etc/sudoers.d && \
    echo "samba ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/samba && \
    apt-get update -y && \
    apt-get -yq install apt-utils sudo inetutils-ping ncdu vim language-pack-en && \
    update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 && \
    apt-get -yq install {% for item in packages %}{{item}} {% endfor %} && \
    apt-get -y clean && \
    apt-get -y autoremove && \
    ln -sf /usr/bin/ld.gold /usr/bin/ld

USER samba
WORKDIR /home/samba
