FROM {{ SAMBA_BASE_IMAGE }}

ENV PYTHONPATH="{{SAMBA_REPO_DIR}}/bin/python"
ENV PATH=/usr/local/samba/bin:/usr/local/samba/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin

RUN mkdir -p {{SAMBA_REPO_DIR}}
WORKDIR {{SAMBA_REPO_DIR}}

RUN git clone --depth 30 --branch {{SAMBA_REPO_VERSION}} {{SAMBA_REPO_URL}} . && ./configure.developer && make -j && sudo make install
