---
version: "3"

services:
  dc0:
    image: samba-dc
    container_name: dc0
    hostname: dc0
    user: samba
    command: sudo /usr/local/samba/sbin/samba --interactive --debuglevel=3
    volumes:
      - .:{{ SAMBA_VOLUME }}
    working_dir: /home/samba/samba
    dns_search:
      - "{{ SAMBA_REALM|lower }}"
    domainname: "{{ SAMBA_REALM|lower }}"
    stdin_open: true
    tty: true
