FROM {{SAMBA_BASE_IMAGE}}

# we will use this image to run ci, these ENV vars are important
ENV USER=samba CC="ccache gcc"
ENV LANGUAGE=en_US:en LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

ADD ./samba-bootstrap.sh /tmp/
# need root permission, do it before USER samba
RUN bash /tmp/samba-bootstrap.sh

# make test can not work with root, so we have to create a new user
RUN useradd -m -s /bin/bash samba && \
    mkdir -p /etc/sudoers.d && \
    echo "samba ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/samba

USER samba
WORKDIR /home/samba
