FROM samba-env

ENV PYTHONPATH="{{SAMBA_REPO_DIR}}/bin/python"

# will create if not exist
WORKDIR {{SAMBA_REPO_DIR}}

RUN git clone --depth 30 --branch {{SAMBA_REPO_BRANCH}} {{SAMBA_REPO_URL}} . && \
    ./configure.developer && make -j && make install

# add util scripts
ADD *.sh ./
RUN chmod a+x *.sh

CMD /usr/local/samba/sbin/samba -F -i
